server:
  port: 8080
  error:
    whitelabel:
      enabled: true
    include-exception: true
    include-stacktrace: always

logging:
  level:
    root: INFO
    com.fourtime: DEBUG
    org.flywaydb: DEBUG
    org.springframework.data: DEBUG
    org.springframework.jdbc: DEBUG

spring:
  http:
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    default-property-inclusion: non_empty
    serialization:
      indent-output: false
    mapper:
      default-view-inclusion: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:3000
